# https://garafu.blogspot.com/2017/02/eslint-rules-jp.html
env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 4
  # linebreak-style:
    # - error
    # - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - 0
